default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['POSTGRES_USER'] || 'postgres' %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] || 'localhost' %>
  pool: 50

development:
  <<: *default
  database: radio_playlists_development

test:
  <<: *default
  database: radio_playlists_test

production:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

staging:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>
  url: <%= ENV['POSTGRES_URL'] %>
